<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kimulator.Core\Kimulator.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\roms\6530-002.bin" LogicalName="Kimulator.Kim1.Roms.6530-002.bin" />
    <EmbeddedResource Include="..\..\assets\roms\6530-003.bin" LogicalName="Kimulator.Kim1.Roms.6530-003.bin" />
    <EmbeddedResource Include="Symbols\kim1-monitor.sym" LogicalName="Kimulator.Kim1.Symbols.kim1-monitor.sym" />
  </ItemGroup>

</Project>
